old version

In [1]:
import pandas as pd

def clean_data(df):
    # Filter rows based on columns: 'technology', 'scenario_geography'
    df = df[(df['technology'].str.contains("gascap", regex=False, na=False, case=False)) & (df['scenario_geography'].str.contains("R10MIDDLE_EAST", regex=False, na=False, case=False))]
    df = df.assign(npv_diff = df["latesudden_npv"] - df["baseline_npv"])
    # Performed 2 aggregations grouped on columns: 'sector', 'technology', 'scenario_geography'
    df = df.groupby(['sector', 'technology', 'scenario_geography']).agg(baseline_npv_sum=('baseline_npv', 'sum'), latesudden_npv_sum=('latesudden_npv', 'sum')).reset_index()
    df = df.assign(npv_diff = df["latesudden_npv_sum"] - df["baseline_npv_sum"])
    return df

# Loaded variable 'df' from URI: /Users/bertrandgallice/code/Theia-Finance-Labs/crispy-kedro/workspace/results_V8/REMIND-MAgPIE_DeepElec__asset_granularity_with_staggered_shock_and_retirement/asset_npv.csv
df = pd.read_csv(r'/Users/bertrandgallice/code/Theia-Finance-Labs/crispy-kedro/workspace/results_V8/REMIND-MAgPIE_DeepElec__asset_granularity_with_staggered_shock_and_retirement/asset_npv.csv')

df_clean1 = clean_data(df.copy())
df_clean1.head()

,sector,technology,scenario_geography,baseline_npv_sum,latesudden_npv_sum,npv_diff
0,Power,GasCap - w/o CCS,R10MIDDLE_EAST,-3.353151e+11,-1.931785e+11,1.421367e+11

new version

In [2]:
# Loaded variable 'df' from URI: /Users/bertrandgallice/code/Theia-Finance-Labs/crispy-kedro/workspace/results_V9/IMACLIM_ADVANCE__asset_granularity_with_staggered_shock_and_retirement/asset_npv.csv
import pandas as pd
df = pd.read_csv(r'/Users/bertrandgallice/code/Theia-Finance-Labs/crispy-kedro/workspace/results_V9/IMACLIM_ADVANCE__asset_granularity_with_staggered_shock_and_retirement/asset_npv.csv')


# Filter rows based on columns: 'technology', 'scenario_geography'
df = df[(df['technology'].str.contains("gascap", regex=False, na=False, case=False)) & (df['scenario_geography'].str.contains("R10MIDDLE_EAST", regex=False, na=False, case=False))]

df = df.assign(npv_diff = df["latesudden_npv"] - df["baseline_npv"])

# Performed 2 aggregations grouped on columns: 'sector', 'technology', 'scenario_geography'
df = df.groupby(['sector', 'technology', 'scenario_geography']).agg(baseline_npv_sum=('baseline_npv', 'sum'), latesudden_npv_sum=('latesudden_npv', 'sum')).reset_index()

df_clean2 = df.assign(npv_diff = df["latesudden_npv_sum"] - df["baseline_npv_sum"])

combine

In [8]:
df_combined = pd.concat([df_clean1, df_clean2])

df_combined.insert(
    0, "scenario_provider" ,  ["REMIND", "IMACLIM"]
    )
df_combined.head()

,scenario_provider,sector,technology,scenario_geography,baseline_npv_sum,latesudden_npv_sum,npv_diff
0,REMIND,Power,GasCap - w/o CCS,R10MIDDLE_EAST,-3.353151e+11,-1.931785e+11,1.421367e+11
0,IMACLIM,Power,GasCap - w/o CCS,R10MIDDLE_EAST,9.351834e+11,5.926075e+11,-3.425759e+11