In [1]:
from pathlib import Path
from kedro.framework.session import KedroSession
from kedro.framework.startup import bootstrap_project
import pandas as pd
import os

[04/08/25 10:02:53] INFO     Using                                                                  ]8;id=595536;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/framework/project/__init__.py\__init__.py]8;;\:]8;id=638827;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/framework/project/__init__.py#270\270]8;;\
                             '/Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-pa
                             ckages/kedro/framework/project/rich_logging.yml' as logging
                             configuration.

In [2]:
os.environ["KEDRO_PACKAGE_NAME"] = "crispy_kedro"

# Since the notebook is in ./notebooks, set the project path to the parent directory
os.chdir(Path.cwd().parent)

metadata = bootstrap_project(project_path=Path.cwd())

[04/08/25 10:02:55] WARNING  /Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-pac ]8;id=878324;file:///Users/bertrandgallice/.pyenv/versions/3.10.12/lib/python3.10/warnings.py\warnings.py]8;;\:]8;id=956051;file:///Users/bertrandgallice/.pyenv/versions/3.10.12/lib/python3.10/warnings.py#109\109]8;;\
                             kages/kedro/io/data_catalog.py:165: KedroDeprecationWarning:
                             `DataCatalog` has been deprecated and will be replaced by
                             `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog`
                             APIs have been retained for compatibility with `DataCatalog`,
                             including the `datasets` property and the `get_datasets`,
                             `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy`
                             methods. These will be removed or replaced with updated alternatives
                             in Kedro 1.0.0. For more details, refer to the documentation:
                             https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-expe
                             rimental-feature
                               warnings.warn(

In [3]:
# Define your parameter overrides
extra_params = {
    "baseline_scenario": "NGFS2024_GCAM_CP",
    "target_scenario": "NGFS2024_GCAM_NZ2050",
    "scenario_geography": "Global",
    "shock_year": 2040,
    "forecast_horizon": 20,
    "discount_rate": 0.07,
    "growth_rate": 0.03,
    "asset_ids": [
        # "L100000104929",
        # "L100001004877",
        # "L100000829070",
        # "L100000909305",
        # "L100000401784",
        # "L100000832788",
        # "L100000101255",
        # "L100001004028",
        # "L100000917865",
        # "L100000814519",
        # "L100000820130",
        # "L100000820067",
        # "L100000808475",
        # "L603844",
        # "L100001010934",
        # "L100001003089"
    ]
}

In [4]:
# Cell 3: Create and run the Kedro session
with KedroSession.create(
    project_path=Path.cwd(),
    extra_params=extra_params
) as session:
    session.run(pipeline_name="trisk")

[04/08/25 10:02:55] INFO     Kedro project crispy-kedro                                              ]8;id=494731;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/framework/session/session.py\session.py]8;;\:]8;id=433281;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/framework/session/session.py#329\329]8;;\

[04/08/25 10:02:56] WARNING  /Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-pac ]8;id=509866;file:///Users/bertrandgallice/.pyenv/versions/3.10.12/lib/python3.10/warnings.py\warnings.py]8;;\:]8;id=690445;file:///Users/bertrandgallice/.pyenv/versions/3.10.12/lib/python3.10/warnings.py#109\109]8;;\
                             kages/kedro/io/data_catalog.py:165: KedroDeprecationWarning:
                             `DataCatalog` has been deprecated and will be replaced by
                             `KedroDataCatalog`, in Kedro 1.0.0.Currently some `KedroDataCatalog`
                             APIs have been retained for compatibility with `DataCatalog`,
                             including the `datasets` property and the `get_datasets`,
                             `_get_datasets`, `add`,` list`, `add_feed_dict`, and `shallow_copy`
                             methods. These will be removed or replaced with updated alternatives
                             in Kedro 1.0.0. For more details, refer to the documentation:
                             https://docs.kedro.org/en/stable/data/index.html#kedrodatacatalog-expe
                             rimental-feature
                               warnings.warn(

                    INFO     Using synchronous mode for loading and saving data. Use the    ]8;id=12735;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/sequential_runner.py\sequential_runner.py]8;;\:]8;id=400595;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/sequential_runner.py#68\68]8;;\
                             --async flag for potential performance gains.
                             https://docs.kedro.org/en/stable/nodes_and_pipelines/run_a_pip
                             eline.html#load-and-save-asynchronously

                    INFO     Loading data from plant_detail (TableDataset)...                   ]8;id=908171;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=959427;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#401\401]8;;\

                    INFO     Loading data from plant_events (TableDataset)...                   ]8;id=599013;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=992754;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#401\401]8;;\

                    INFO     Loading data from params:asset_ids (MemoryDataset)...              ]8;id=727845;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=412229;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#401\401]8;;\

                    INFO     Running node: filter_assets() ->                                           ]8;id=589566;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/pipeline/node.py\node.py]8;;\:]8;id=679803;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/pipeline/node.py#367\367]8;;\

[04/08/25 10:03:06] INFO     Saving data to filtered_plant_detail (MemoryDataset)...            ]8;id=934987;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=246702;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#443\443]8;;\

                    INFO     Saving data to filtered_events (MemoryDataset)...                  ]8;id=510112;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=543649;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#443\443]8;;\

                    INFO     Completed node: filter_assets() ->                                       ]8;id=446154;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py\runner.py]8;;\:]8;id=424287;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py#244\244]8;;\

                    INFO     Completed 1 out of 30 tasks                                              ]8;id=203329;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py\runner.py]8;;\:]8;id=896140;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py#245\245]8;;\

                    INFO     Loading data from scenarios (TableDataset)...                      ]8;id=606498;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=622986;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#401\401]8;;\

                    INFO     Loading data from params:baseline_scenario (MemoryDataset)...      ]8;id=147422;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=559604;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#401\401]8;;\

                    INFO     Loading data from params:target_scenario (MemoryDataset)...        ]8;id=269035;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=145500;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#401\401]8;;\

                    INFO     Loading data from params:scenario_geography (MemoryDataset)...     ]8;id=524742;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=475904;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#401\401]8;;\

                    INFO     Running node: filter_scenarios() ->                                        ]8;id=244884;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/pipeline/node.py\node.py]8;;\:]8;id=619977;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/pipeline/node.py#367\367]8;;\

[04/08/25 10:03:07] INFO     Saving data to traj_scenario (MemoryDataset)...                    ]8;id=772926;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=458367;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#443\443]8;;\

                    INFO     Completed node: filter_scenarios() ->                                    ]8;id=351382;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py\runner.py]8;;\:]8;id=933420;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py#244\244]8;;\

                    INFO     Completed 2 out of 30 tasks                                              ]8;id=32794;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py\runner.py]8;;\:]8;id=557010;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py#245\245]8;;\

                    INFO     Loading data from scenarios (TableDataset)...                      ]8;id=271363;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=70145;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#401\401]8;;\

                    INFO     Running node: make_scenarios_data() ->                                     ]8;id=851498;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/pipeline/node.py\node.py]8;;\:]8;id=33445;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/pipeline/node.py#367\367]8;;\

[04/08/25 10:03:08] INFO     Saving data to scenarios_data (ExcelDataset)...                    ]8;id=502845;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=205116;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#443\443]8;;\

[04/08/25 10:03:17] INFO     Completed node: make_scenarios_data() ->                                 ]8;id=422863;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py\runner.py]8;;\:]8;id=525295;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py#244\244]8;;\

                    INFO     Completed 3 out of 30 tasks                                              ]8;id=687314;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py\runner.py]8;;\:]8;id=201302;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py#245\245]8;;\

                    INFO     Loading data from traj_scenario (MemoryDataset)...                 ]8;id=454590;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=832788;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#401\401]8;;\

                    INFO     Loading data from params:shock_year (MemoryDataset)...             ]8;id=220404;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=175578;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#401\401]8;;\

                    INFO     Running node: build_price_trajectory() ->                                  ]8;id=277320;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/pipeline/node.py\node.py]8;;\:]8;id=406472;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/pipeline/node.py#367\367]8;;\

                    INFO     Saving data to traj_technology_prices (MemoryDataset)...           ]8;id=447787;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=810079;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#443\443]8;;\

                    INFO     Completed node: build_price_trajectory() ->                              ]8;id=744807;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py\runner.py]8;;\:]8;id=153159;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py#244\244]8;;\

                    INFO     Completed 4 out of 30 tasks                                              ]8;id=46954;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py\runner.py]8;;\:]8;id=584092;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py#245\245]8;;\

                    INFO     Loading data from traj_scenario (MemoryDataset)...                 ]8;id=366788;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=899519;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#401\401]8;;\

                    INFO     Running node: calculate_fair_share_perc() ->                               ]8;id=473799;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/pipeline/node.py\node.py]8;;\:]8;id=245961;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/pipeline/node.py#367\367]8;;\

                    INFO     Saving data to traj_scenario_baseline (MemoryDataset)...           ]8;id=962670;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=804518;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#443\443]8;;\

                    INFO     Saving data to traj_scenario_target (MemoryDataset)...             ]8;id=996219;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=594412;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#443\443]8;;\

                    INFO     Completed node: calculate_fair_share_perc() ->                           ]8;id=975061;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py\runner.py]8;;\:]8;id=323181;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py#244\244]8;;\

                    INFO     Completed 5 out of 30 tasks                                              ]8;id=697603;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py\runner.py]8;;\:]8;id=123419;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py#245\245]8;;\

                    INFO     Loading data from filtered_plant_detail (MemoryDataset)...         ]8;id=45046;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=91704;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#401\401]8;;\

                    INFO     Loading data from filtered_events (MemoryDataset)...               ]8;id=678779;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=542318;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#401\401]8;;\

                    INFO     Running node: compute_raw_trajectory() ->                                  ]8;id=147874;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/pipeline/node.py\node.py]8;;\:]8;id=835494;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/pipeline/node.py#367\367]8;;\

Processing assets x tech: 100%|██████████| 81057/81057 [02:33<00:00, 527.03it/s]

[04/08/25 10:06:03] INFO     Saving data to traj_assets_raw (MemoryDataset)...                  ]8;id=110459;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=389535;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#443\443]8;;\

[04/08/25 10:06:04] INFO     Completed node: compute_raw_trajectory() ->                              ]8;id=969673;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py\runner.py]8;;\:]8;id=395979;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py#244\244]8;;\

                    INFO     Completed 6 out of 30 tasks                                              ]8;id=133113;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py\runner.py]8;;\:]8;id=730485;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py#245\245]8;;\

                    INFO     Loading data from plant_ownerships (TableDataset)...               ]8;id=272603;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=275555;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#401\401]8;;\

                    INFO     Loading data from filtered_plant_detail (MemoryDataset)...         ]8;id=454240;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=371122;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#401\401]8;;\

                    INFO     Running node: filter_companies() ->                                        ]8;id=689351;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/pipeline/node.py\node.py]8;;\:]8;id=754237;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/pipeline/node.py#367\367]8;;\

[04/08/25 10:06:26] INFO     Saving data to companies_ownership_tree (MemoryDataset)...         ]8;id=292148;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=267369;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#443\443]8;;\

                    INFO     Completed node: filter_companies() ->                                    ]8;id=416996;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py\runner.py]8;;\:]8;id=363849;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py#244\244]8;;\

                    INFO     Completed 7 out of 30 tasks                                              ]8;id=106303;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py\runner.py]8;;\:]8;id=871853;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py#245\245]8;;\

                    INFO     Loading data from traj_assets_raw (MemoryDataset)...               ]8;id=639351;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=493164;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#401\401]8;;\

[04/08/25 10:06:27] INFO     Loading data from traj_scenario (MemoryDataset)...                 ]8;id=62226;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=887041;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#401\401]8;;\

                    INFO     Loading data from params:forecast_horizon (MemoryDataset)...       ]8;id=858438;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=831605;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#401\401]8;;\

                    INFO     Running node: truncate_traj_asset() ->                                     ]8;id=694640;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/pipeline/node.py\node.py]8;;\:]8;id=496326;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/pipeline/node.py#367\367]8;;\

[04/08/25 10:06:32] ERROR    Node truncate_traj_asset() ->  failed with error:                          ]8;id=940353;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/pipeline/node.py\node.py]8;;\:]8;id=525425;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/pipeline/node.py#392\392]8;;\
                             cannot handle a non-unique multi-index!

                    WARNING  There are 23 nodes that have not run.                                    ]8;id=788423;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py\runner.py]8;;\:]8;id=281211;file:///Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner.py#338\338]8;;\
                             You can resume the pipeline run from the nearest nodes with persisted
                             inputs by adding the following argument to your previous command:
                               --from-nodes "filter_assets() -> ,filter_scenarios() -> "

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:6                                                                                    │
│                                                                                                  │
│   3 │   project_path=Path.cwd(),                                                                 │
│   4 │   extra_params=extra_params                                                                │
│   5 ) as session:                                                                                │
│ ❱ 6 │   session.run(pipeline_name="trisk")                                                       │
│   7                                                                                              │
│                                                                                                  │
│ /Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/framework/sess │
│ ion/session.py:399 in run                                                                        │
│                                                                                                  │
│   396 │   │   │   run_params=record_data, pipeline=filtered_pipeline, catalog=catalog            │
│   397 │   │   )                                                                                  │
│   398 │   │   try:                                                                               │
│ ❱ 399 │   │   │   run_result = runner.run(                                                       │
│   400 │   │   │   │   filtered_pipeline, catalog, hook_manager, session_id                       │
│   401 │   │   │   )                                                                              │
│   402 │   │   │   self._run_called = True                                                        │
│                                                                                                  │
│ /Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner. │
│ py:129 in run                                                                                    │
│                                                                                                  │
│   126 │   │   │   │   "Asynchronous mode is enabled for loading and saving data"                 │
│   127 │   │   │   )                                                                              │
│   128 │   │                                                                                      │
│ ❱ 129 │   │   self._run(pipeline, catalog, hook_or_null_manager, session_id)  # type: ignore[a   │
│   130 │   │                                                                                      │
│   131 │   │   self._logger.info("Pipeline execution completed successfully.")                    │
│   132                                                                                            │
│                                                                                                  │
│ /Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/sequent │
│ ial_runner.py:72 in _run                                                                         │
│                                                                                                  │
│   69 │   │   │   │   "Using synchronous mode for loading and saving data. Use the --async fla    │
│   70 │   │   │   │   "for potential performance gains. https://docs.kedro.org/en/stable/nodes    │
│   71 │   │   │   )                                                                               │
│ ❱ 72 │   │   super()._run(                                                                       │
│   73 │   │   │   pipeline=pipeline,                                                              │
│   74 │   │   │   catalog=catalog,                                                                │
│   75 │   │   │   hook_manager=hook_manager,                                                      │
│                                                                                                  │
│ /Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/runner. │
│ py:239 in _run                                                                                   │
│                                                                                                  │
│   236 │   │   │   │   │   │   hook_manager=hook_manager,                                         │
│   237 │   │   │   │   │   │   is_async=self._is_async,                                           │
│   238 │   │   │   │   │   │   session_id=session_id,                                             │
│ ❱ 239 │   │   │   │   │   ).execute()                                                            │
│   240 │   │   │   │   │   done_nodes.add(node)                                                   │
│   241 │   │   │   │   except Exception:                                                          │
│   242 │   │   │   │   │   self._suggest_resume_scenario(pipeline, done_nodes, catalog)           │
│                                                                                                  │
│ /Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/task.py │
│ :88 in execute                                                                                   │
│                                                                                                  │
│    85 │   │   │   │   self.session_id,                                                           │
│    86 │   │   │   )                                                                              │
│    87 │   │   else:                                                                              │
│ ❱  88 │   │   │   node = self._run_node_sequential(                                              │
│    89 │   │   │   │   self.node,                                                                 │
│    90 │   │   │   │   self.catalog,                                                              │
│    91 │   │   │   │   self.hook_manager,  # type: ignore[arg-type]                               │
│                                                                                                  │
│ /Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/task.py │
│ :164 in _run_node_sequential                                                                     │
│                                                                                                  │
│   161 │   │   )                                                                                  │
│   162 │   │   inputs.update(additional_inputs)                                                   │
│   163 │   │                                                                                      │
│ ❱ 164 │   │   outputs = self._call_node_run(                                                     │
│   165 │   │   │   node, catalog, inputs, is_async, hook_manager, session_id=session_id           │
│   166 │   │   )                                                                                  │
│   167                                                                                            │
│                                                                                                  │
│ /Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/task.py │
│ :308 in _call_node_run                                                                           │
│                                                                                                  │
│   305 │   │   │   │   is_async=is_async,                                                         │
│   306 │   │   │   │   session_id=session_id,                                                     │
│   307 │   │   │   )                                                                              │
│ ❱ 308 │   │   │   raise exc                                                                      │
│   309 │   │   hook_manager.hook.after_node_run(                                                  │
│   310 │   │   │   node=node,                                                                     │
│   311 │   │   │   catalog=catalog,                                                               │
│                                                                                                  │
│ /Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/runner/task.py │
│ :298 in _call_node_run                                                                           │
│                                                                                                  │
│   295 │   │   session_id: str | None = None,                                                     │
│   296 │   ) -> dict[str, Any]:                                                                   │
│   297 │   │   try:                                                                               │
│ ❱ 298 │   │   │   outputs = node.run(inputs)                                                     │
│   299 │   │   except Exception as exc:                                                           │
│   300 │   │   │   hook_manager.hook.on_node_error(                                               │
│   301 │   │   │   │   error=exc,                                                                 │
│                                                                                                  │
│ /Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/pipeline/node. │
│ py:398 in run                                                                                    │
│                                                                                                  │
│   395 │   │   │   │   str(exc),                                                                  │
│   396 │   │   │   │   extra={"markup": True},                                                    │
│   397 │   │   │   )                                                                              │
│ ❱ 398 │   │   │   raise exc                                                                      │
│   399 │                                                                                          │
│   400 │   def _run_with_no_inputs(self, inputs: dict[str, Any]) -> Any:                          │
│   401 │   │   if inputs:                                                                         │
│                                                                                                  │
│ /Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/pipeline/node. │
│ py:384 in run                                                                                    │
│                                                                                                  │
│   381 │   │   │   elif isinstance(self._inputs, str):                                            │
│   382 │   │   │   │   outputs = self._run_with_one_input(inputs, self._inputs)                   │
│   383 │   │   │   elif isinstance(self._inputs, list):                                           │
│ ❱ 384 │   │   │   │   outputs = self._run_with_list(inputs, self._inputs)                        │
│   385 │   │   │   elif isinstance(self._inputs, dict):                                           │
│   386 │   │   │   │   outputs = self._run_with_dict(inputs, self._inputs)                        │
│   387                                                                                            │
│                                                                                                  │
│ /Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/kedro/pipeline/node. │
│ py:429 in _run_with_list                                                                         │
│                                                                                                  │
│   426 │   │   │   │   f"{sorted(inputs.keys())}."                                                │
│   427 │   │   │   )                                                                              │
│   428 │   │   # Ensure the function gets the inputs in the correct order                         │
│ ❱ 429 │   │   return self._func(*(inputs[item] for item in node_inputs))                         │
│   430 │                                                                                          │
│   431 │   def _run_with_dict(                                                                    │
│   432 │   │   self, inputs: dict[str, Any], node_inputs: dict[str, str]                          │
│                                                                                                  │
│ /Users/bertrandgallice/code/crispy-kedro/src/crispy_kedro/pipelines/trisk/nodes/assets_trajector │
│ ies.py:151 in truncate_traj_asset                                                                │
│                                                                                                  │
│   148 │   # Reindex the base trajectory to the full index                                        │
│   149 │   df_full = (                                                                            │
│   150 │   │   raw_trajectory.set_index(["asset_id", "sector", "technology", "year"])             │
│ ❱ 151 │   │   .reindex(multi_index)                                                              │
│   152 │   │   .sort_index()                                                                      │
│   153 │   │   .reset_index()                                                                     │
│   154 │   )                                                                                      │
│                                                                                                  │
│ /Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/pandas/core/frame.py │
│ :5378 in reindex                                                                                 │
│                                                                                                  │
│    5375 │   │   limit: int | None = None,                                                        │
│    5376 │   │   tolerance=None,                                                                  │
│    5377 │   ) -> DataFrame:                                                                      │
│ ❱  5378 │   │   return super().reindex(                                                          │
│    5379 │   │   │   labels=labels,                                                               │
│    5380 │   │   │   index=index,                                                                 │
│    5381 │   │   │   columns=columns,                                                             │
│                                                                                                  │
│ /Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/pandas/core/generic. │
│ py:5610 in reindex                                                                               │
│                                                                                                  │
│    5607 │   │   │   return self._reindex_multi(axes, copy, fill_value)                           │
│    5608 │   │                                                                                    │
│    5609 │   │   # perform the reindex on the axes                                                │
│ ❱  5610 │   │   return self._reindex_axes(                                                       │
│    5611 │   │   │   axes, level, limit, tolerance, method, fill_value, copy                      │
│    5612 │   │   ).__finalize__(self, method="reindex")                                           │
│    5613                                                                                          │
│                                                                                                  │
│ /Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/pandas/core/generic. │
│ py:5633 in _reindex_axes                                                                         │
│                                                                                                  │
│    5630 │   │   │   │   continue                                                                 │
│    5631 │   │   │                                                                                │
│    5632 │   │   │   ax = self._get_axis(a)                                                       │
│ ❱  5633 │   │   │   new_index, indexer = ax.reindex(                                             │
│    5634 │   │   │   │   labels, level=level, limit=limit, tolerance=tolerance, method=method     │
│    5635 │   │   │   )                                                                            │
│    5636                                                                                          │
│                                                                                                  │
│ /Users/bertrandgallice/code/crispy-kedro/.venv/lib/python3.10/site-packages/pandas/core/indexes/ │
│ base.py:4426 in reindex                                                                          │
│                                                                                                  │
│   4423 │   │   │   │   │   │   target, method=method, limit=limit, tolerance=tolerance           │
│   4424 │   │   │   │   │   )                                                                     │
│   4425 │   │   │   │   elif self._is_multi:                                                      │
│ ❱ 4426 │   │   │   │   │   raise ValueError("cannot handle a non-unique multi-index!")           │
│   4427 │   │   │   │   elif not self.is_unique:                                                  │
│   4428 │   │   │   │   │   # GH#42568                                                            │
│   4429 │   │   │   │   │   raise ValueError("cannot reindex on an axis with duplicate labels")   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: cannot handle a non-unique multi-index!

In [ ]:
company_trajectories = pd.read_excel("data/08_reporting/companies_net_profits.xlsx")
company_trajectories

,company_id,sector,technology,year,company_trajectory_baseline,net_profits_baseline,discounted_net_profit_baseline,company_trajectory_shock,net_profits_shock,discounted_net_profit_shock
0,1a346e95a83e6225f4d2bb455eee1c52,Power,CoalCap,2023,660.000000,4327.482512,4327.482512,3.217820e+06,2.109858e+07,2.109858e+07
1,1a346e95a83e6225f4d2bb455eee1c52,Power,CoalCap,2024,660.000000,4323.973608,4041.096830,3.230482e+06,2.116442e+07,1.977983e+07
2,1a346e95a83e6225f4d2bb455eee1c52,Power,CoalCap,2025,1320.000000,8641.450293,7547.777354,6.486779e+06,4.246605e+07,3.709149e+07
3,1a346e95a83e6225f4d2bb455eee1c52,Power,CoalCap,2026,1320.000000,8635.435246,7049.087458,6.508616e+06,4.257934e+07,3.475743e+07
4,1a346e95a83e6225f4d2bb455eee1c52,Power,CoalCap,2027,1320.000000,8629.866041,6583.683483,6.531254e+06,4.269988e+07,3.257553e+07
...,...,...,...,...,...,...,...,...,...,...
343,d228b814ff052635f7acb253fb5e6cd8,Power,RenewablesCap,2047,4.528990,24.089743,4.749211,0.000000e+00,0.000000e+00,0.000000e+00
344,d228b814ff052635f7acb253fb5e6cd8,Power,RenewablesCap,2048,4.660040,24.633750,4.538748,0.000000e+00,0.000000e+00,0.000000e+00
345,d228b814ff052635f7acb253fb5e6cd8,Power,RenewablesCap,2049,4.791448,25.174991,4.335020,0.000000e+00,0.000000e+00,0.000000e+00
346,d228b814ff052635f7acb253fb5e6cd8,Power,RenewablesCap,2050,4.922498,25.709757,4.137481,0.000000e+00,0.000000e+00,0.000000e+00
347,d228b814ff052635f7acb253fb5e6cd8,Power,RenewablesCap,2051,4.922498,26.481050,662.026243,0.000000e+00,0.000000e+00,0.000000e+00

In [ ]:
assets_input_data = pd.read_excel("data/08_reporting/traj_assets_raw_truncated.xlsx")
assets_input_data

          asset_id sector technology  year  asset_trajectory
0    L100000101255  Power    CoalCap  2023             400.0
1    L100000101255  Power    CoalCap  2024             400.0
2    L100000101255  Power    CoalCap  2025             400.0
3    L100000101255  Power    CoalCap  2026             400.0
4    L100000101255  Power    CoalCap  2027             400.0
..             ...    ...        ...   ...               ...
331        L603844  Power   HydroCap  2039             177.0
332        L603844  Power   HydroCap  2040             177.0
333        L603844  Power   HydroCap  2041             177.0
334        L603844  Power   HydroCap  2042             177.0
335        L603844  Power   HydroCap  2043             177.0

[336 rows x 5 columns]