In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/07_model_output/scenarios_pathways_clean.csv")

In [3]:
df["price_ratio"] = df["scenario_price_scaled"] / df["scenario_price"]

In [4]:
result = df.groupby(["scenario", "scenario_type","scenario_geography", "technology"])["price_ratio"].agg([
    ('mean', 'mean'),
    ('median', 'median'),
    ('min', 'min'),
    ('max', 'max'),
    ('percentile_2.5', lambda x: x.quantile(0.025)),
    ('percentile_5', lambda x: x.quantile(0.05)),
    ('percentile_95', lambda x: x.quantile(0.95)),
    ('percentile_97.5', lambda x: x.quantile(0.975))
]).reset_index()
result = result.sort_values(by=["technology", "scenario_geography", "scenario"], ascending=False)
result

,scenario,scenario_type,scenario_geography,technology,mean,median,min,max,percentile_2.5,percentile_5,percentile_95,percentile_97.5
467,AR6_REMIND-MAgPIE 2.1-4.3_DeepElec_SSP2_Base,baseline,USA,SolarCap - PV,1.351417,1.328741,1.288266,1.545058,1.290113,1.292184,1.490919,1.517728
233,AR6_REMIND-MAgPIE 2.1-4.3_DeepElec_SSP2_ HighR...,target,USA,SolarCap - PV,1.707099,1.653820,1.107988,2.445434,1.120449,1.133854,2.369358,2.407052
454,AR6_REMIND-MAgPIE 2.1-4.3_DeepElec_SSP2_Base,baseline,RUS,SolarCap - PV,1.353353,1.330699,1.129799,1.657724,1.136354,1.142090,1.617676,1.637574
220,AR6_REMIND-MAgPIE 2.1-4.3_DeepElec_SSP2_ HighR...,target,RUS,SolarCap - PV,1.504073,1.442473,1.181881,2.084316,1.188622,1.199856,1.997683,2.040458
441,AR6_REMIND-MAgPIE 2.1-4.3_DeepElec_SSP2_Base,baseline,R10ROWO,SolarCap - PV,1.955574,1.914187,1.837747,2.346337,1.842687,1.847697,2.238666,2.291832
...,...,...,...,...,...,...,...,...,...,...,...,...
26,AR6_REMIND-MAgPIE 2.1-4.3_DeepElec_SSP2_ HighR...,target,Global,BiomassCap,2.774081,2.206121,1.721744,4.788793,1.742545,1.764112,4.604423,4.696335
247,AR6_REMIND-MAgPIE 2.1-4.3_DeepElec_SSP2_Base,baseline,EU,BiomassCap,1.222643,1.160302,0.719846,1.708609,0.750130,0.780377,1.676631,1.692484
13,AR6_REMIND-MAgPIE 2.1-4.3_DeepElec_SSP2_ HighR...,target,EU,BiomassCap,3.253463,2.713581,1.628391,5.959391,1.629354,1.637195,5.759826,5.859253
234,AR6_REMIND-MAgPIE 2.1-4.3_DeepElec_SSP2_Base,baseline,CHN,BiomassCap,1.887363,2.051679,1.237559,2.266151,1.272066,1.306933,2.221227,2.239216
0,AR6_REMIND-MAgPIE 2.1-4.3_DeepElec_SSP2_ HighR...,target,CHN,BiomassCap,2.792662,2.591881,1.937517,4.162890,1.945996,1.954976,4.039578,4.101179

In [5]:
result.to_csv("../price_scaling_ratios.csv", index=False)

In [6]:
result = df.groupby(["scenario", "scenario_type","scenario_geography", "technology"])["scenario_price_scaled"].agg([
    ('mean', 'mean'),
    ('median', 'median'),
    ('min', 'min'),
    ('max', 'max'),
    ('percentile_2.5', lambda x: x.quantile(0.025)),
    ('percentile_5', lambda x: x.quantile(0.05)),
    ('percentile_95', lambda x: x.quantile(0.95)),
    ('percentile_97.5', lambda x: x.quantile(0.975))
]).reset_index()
result = result.sort_values(by=["technology", "scenario_geography", "scenario"], ascending=False)
result

,scenario,scenario_type,scenario_geography,technology,mean,median,min,max,percentile_2.5,percentile_5,percentile_95,percentile_97.5
467,AR6_REMIND-MAgPIE 2.1-4.3_DeepElec_SSP2_Base,baseline,USA,SolarCap - PV,89.112123,84.740827,79.074794,105.186925,79.242871,79.409049,104.712769,104.950107
233,AR6_REMIND-MAgPIE 2.1-4.3_DeepElec_SSP2_ HighR...,target,USA,SolarCap - PV,108.096840,91.149204,87.811609,199.377940,87.955586,88.244904,180.285876,189.806928
454,AR6_REMIND-MAgPIE 2.1-4.3_DeepElec_SSP2_Base,baseline,RUS,SolarCap - PV,70.084825,69.374408,64.339737,86.761973,64.392902,64.446123,80.774592,83.721212
220,AR6_REMIND-MAgPIE 2.1-4.3_DeepElec_SSP2_ HighR...,target,RUS,SolarCap - PV,115.356479,97.127854,93.702307,159.659147,93.977403,94.253536,159.323910,159.601139
441,AR6_REMIND-MAgPIE 2.1-4.3_DeepElec_SSP2_Base,baseline,R10ROWO,SolarCap - PV,115.327323,117.205367,95.657235,137.408507,96.734106,97.817549,132.961496,135.159484
...,...,...,...,...,...,...,...,...,...,...,...,...
26,AR6_REMIND-MAgPIE 2.1-4.3_DeepElec_SSP2_ HighR...,target,Global,BiomassCap,200.338249,206.134265,134.061500,267.382261,134.615578,135.742922,259.479383,263.430802
247,AR6_REMIND-MAgPIE 2.1-4.3_DeepElec_SSP2_Base,baseline,EU,BiomassCap,82.472845,79.845154,44.404138,114.752318,46.318830,48.233522,113.886079,114.313823
13,AR6_REMIND-MAgPIE 2.1-4.3_DeepElec_SSP2_ HighR...,target,EU,BiomassCap,195.095490,184.132597,129.505550,285.833385,129.760806,130.027055,279.373553,282.603469
234,AR6_REMIND-MAgPIE 2.1-4.3_DeepElec_SSP2_Base,baseline,CHN,BiomassCap,121.593411,129.307491,75.217376,162.710071,77.138665,79.075719,156.496136,159.568625
0,AR6_REMIND-MAgPIE 2.1-4.3_DeepElec_SSP2_ HighR...,target,CHN,BiomassCap,282.028487,279.780066,167.788610,415.910147,175.624294,181.947946,398.629349,407.240082

In [7]:
result.to_csv("../price_scaling_scaled.csv", index=False)